### ISSUE TITLE
mac 下载后无法安装 一直报错

### ISSUE THREAD

**Issue by bianlin** [vuetwo/vuetron#89]
不能完成此操作，因为找不到一个或多个需要的项目。
（错误代码 -43）

**Comment by samanthasalley** [comment]
Hello @bianlin - are you downloading the OSX version from the INSTALLATION.md, or are you cloning and building the app yourself?

If you are cloning and building yourself, please try downloading pre-built version (linked [here](https://github.com/vuetwo/vuetron/blob/master/docs/INSTALLATION.md)) and if you are having trouble with the downloaded version, can you be more specific about the error you're receiving and/or at what point the app is failing?

**Comment by samanthasalley** [comment]
closing - assuming issue is resolved
