### ISSUE TITLE
Installation Docs: wrong ES6 syntax

### ISSUE THREAD

**Issue by psychosis448** [vuetwo/vuetron#91]
The instructions regarding 'Adding Vuetron plugins in your application' seem to be not correct as

```bash
vuetron/packages/vuetron-plugins/index.js
```

only exports the default object.

```javascript
import { VuetronVue } from 'vuetron';
```

and

```javascript
import { VuetronVuex } from 'vuetron';
```

are not possible.

**Comment by yzzting** [comment]
@psychosis448 Hey man. I also encountered the same problem. Do you have a solution?

**Comment by psychosis448** [comment]
You just have to change the import statement accordingly.
So either
```javascript
import VuetronVue from 'vuetron'
```
or
```javascript
import * as VuetronVue from 'vuetron'
```

**Comment by samanthasalley** [comment]
docs have been updated to reflect accurate import instructions
